/*
 * Automatically generated by "tools/bmp_logo"
 *
 * DO NOT EDIT
 *
 */


#ifndef __BMP_LOGO_H__
#define __BMP_LOGO_H__

#define BMP_LOGO_WIDTH		160
#define BMP_LOGO_HEIGHT		96
#define BMP_LOGO_COLORS		31
#define BMP_LOGO_OFFSET		16
#define BMP_LOGO_BITS		-480969138110456
Error allocating memory for file logos/denx.bmp.
